let onLevel = 0
let onGroup = 0
let groups = [
  { numLevels: 12, startNum: 0, title: 'Practice' },
  { numLevels: 12, startNum: 12, title: 'Square it up' },
  /*{ numLevels: 12, startNum: 24, title: 'Circle Drop' },
  { numLevels: 12, startNum: 36, title: 'Ice Break' },
  { numLevels: 12, startNum: 48, title: 'Wild Time' } */
];
let levels = [
  { tittle: "fasfsdf", rows: 8, cols: 5, items: 5, background: 0xfafafa, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 0, allowGem: false, gemsStartCount: 0, movesGoal: 20, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: true, roverStartCount: 4, win: { orange: 4, rover: 3, }, blocks: [{ "row": 1, "col": 1 }, { "row": 1, "col": 2 }, { "row": 2, "col": 1 }, { "row": 2, "col": 2 }] },
  { tittle: "Wild", rows: 8, cols: 7, items: 5, background: 0xfafafa, allowWild: true, wildStartCount: 5, allowDrop: false, dropStartCount: 0, allowGem: false, gemsStartCount: 0, movesGoal: 20, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { orange: 5, green: 10, }, blocks: [] },
  { tittle: "Drop", rows: 8, cols: 7, items: 4, background: 0xfafafa, allowWild: false, wildStartCount: 5, allowDrop: true, dropStartCount: 5, allowGem: false, gemsStartCount: 0, movesGoal: 20, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { orange: 5, green: 10, drop: 3 }, blocks: [] },
  { tittle: "Gem", rows: 8, cols: 7, items: 5, background: 0xfafafa, allowWild: false, wildStartCount: 5, allowDrop: false, dropStartCount: 5, allowGem: true, gemsStartCount: 4, movesGoal: 20, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { orange: 5, green: 10, gem: 3 }, blocks: [] },
  { tittle: "Rover", rows: 8, cols: 7, items: 5, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 0, allowGem: false, gemsStartCount: 0, movesGoal: 20, allowIce: false, iceStartCount: 15, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: true, roverStartCount: 4, win: { blue: 15, orange: 15, rover: 4, }, blocks: [] },
  { tittle: "Ice", rows: 8, cols: 7, items: 5, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 0, allowGem: false, gemsStartCount: 0, movesGoal: 20, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: true, roverStartCount: 4, win: { blue: 15, orange: 15, }, blocks: [] },
  { tittle: "Fire", rows: 8, cols: 7, items: 5, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 0, allowGem: false, gemsStartCount: 0, movesGoal: 20, allowIce: false, iceStartCount: 15, allowFire: true, fireStartCount: 7, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 4, win: { blue: 15, orange: 15, }, blocks: [] },
  { tittle: "Bomb", rows: 8, cols: 7, items: 5, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 0, allowGem: false, gemsStartCount: 0, movesGoal: 20, allowIce: false, iceStartCount: 15, allowFire: false, fireStartCount: 7, allowBomb: true, bombStartCount: 5, allowRover: false, roverStartCount: 4, win: { blue: 15, orange: 15, bomb: 5, }, blocks: [] },
  { tittle: "Square", rows: 8, cols: 7, items: 5, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 0, allowGem: false, gemsStartCount: 0, movesGoal: 20, allowIce: false, iceStartCount: 15, allowFire: false, fireStartCount: 7, allowBomb: false, bombStartCount: 5, allowRover: false, roverStartCount: 4, win: { blue: 15, orange: 15, square: 4, }, blocks: [] },
  { tittle: "Blocks", rows: 8, cols: 7, items: 5, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 0, allowGem: false, gemsStartCount: 0, movesGoal: 20, allowIce: false, iceStartCount: 15, allowFire: false, fireStartCount: 7, allowBomb: false, bombStartCount: 5, allowRover: false, roverStartCount: 4, win: { blue: 15, orange: 15, }, blocks: [{ "row": 3, "col": 2 }, { "row": 3, "col": 3 }, { "row": 3, "col": 4 }, { "row": 4, "col": 2 }, { "row": 4, "col": 3 }, { "row": 4, "col": 4 }] },
  { tittle: "Drop Gem", rows: 8, cols: 7, items: 5, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: true, dropStartCount: 3, allowGem: true, gemsStartCount: 3, movesGoal: 20, allowIce: false, iceStartCount: 15, allowFire: false, fireStartCount: 7, allowBomb: false, bombStartCount: 5, allowRover: false, roverStartCount: 4, win: { blue: 15, orange: 15, drop: 3, gem: 3, }, blocks: [] },
  { tittle: "rover ice", rows: 8, cols: 7, items: 5, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 3, allowGem: false, gemsStartCount: 3, movesGoal: 30, allowIce: true, iceStartCount: 15, allowFire: false, fireStartCount: 7, allowBomb: false, bombStartCount: 5, allowRover: true, roverStartCount: 4, win: { blue: 15, orange: 15, ice: 10, rover: 4 }, blocks: [] },

  { tittle: "1", rows: 6, cols: 4, items: 4, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 3, allowGem: false, gemsStartCount: 0, movesGoal: 10, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 5, orange: 5, purple: 5, }, blocks: [] },
  { tittle: "2", rows: 6, cols: 4, items: 4, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 3, allowGem: false, gemsStartCount: 0, movesGoal: 15, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 10, orange: 10, green: 10, purple: 10, square: 5, }, blocks: [] },
  { tittle: "3", rows: 6, cols: 5, items: 4, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 3, allowGem: false, gemsStartCount: 0, movesGoal: 20, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 10, orange: 20, green: 10, purple: 20, square: 7, }, blocks: [] },
  { tittle: "4", rows: 6, cols: 5, items: 5, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 3, allowGem: false, gemsStartCount: 0, movesGoal: 20, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 15, orange: 15, green: 15, purple: 15, brown: 15, square: 5, }, blocks: [] },
  { tittle: "5", rows: 6, cols: 5, items: 6, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 3, allowGem: false, gemsStartCount: 0, movesGoal: 30, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { red: 15, blue: 15, orange: 15, green: 15, purple: 15, brown: 15, }, blocks: [] },
  { tittle: "6", rows: 6, cols: 6, items: 5, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 3, allowGem: false, gemsStartCount: 0, movesGoal: 25, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 30, orange: 30, green: 30, purple: 30, brown: 30, square: 5, }, blocks: [] },
  { tittle: "7", rows: 6, cols: 6, items: 4, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 3, allowGem: false, gemsStartCount: 0, movesGoal: 25, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 30, orange: 30, green: 30, purple: 30, brown: 30, square: 5, }, blocks: [{ "row": 0, "col": 0 }, { "row": 0, "col": 1 }, { "row": 1, "col": 0 }, { "row": 1, "col": 1 }, { "row": 4, "col": 4 }, { "row": 4, "col": 5 }, { "row": 5, "col": 4 }, { "row": 5, "col": 5 }] },
  { tittle: "8", rows: 6, cols: 4, items: 4, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 3, allowGem: false, gemsStartCount: 0, movesGoal: 25, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { square: 10, }, blocks: [] },
  { tittle: "9", rows: 6, cols: 4, items: 4, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 3, allowGem: false, gemsStartCount: 0, movesGoal: 10, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { square: 5, }, blocks: [] },
  { tittle: "10", rows: 6, cols: 4, items: 5, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 3, allowGem: false, gemsStartCount: 0, movesGoal: 20, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { square: 5, }, blocks: [] },
  { tittle: "11", rows: 6, cols: 4, items: 5, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 3, allowGem: false, gemsStartCount: 0, movesGoal: 20, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 30, purple: 30, square: 5, }, blocks: [] },
  { tittle: "12", rows: 8, cols: 6, items: 5, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: true, dropStartCount: 3, allowGem: false, gemsStartCount: 0, movesGoal: 20, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { orange: 10, drop: 4, }, blocks: [] },

]






