let onLevel = 0
let onGroup = 0
let groups = [
  { numLevels: 12, startNum: 0, title: 'Preview' },
  { numLevels: 12, startNum: 12, title: 'Square it up' },
  { numLevels: 12, startNum: 24, title: 'Drop, Drop' },
  /*{ numLevels: 12, startNum: 36, title: 'Ice Break' },
  { numLevels: 12, startNum: 48, title: 'Wild Time' } */
];
let levels = [
  { tittle: "fasfsdf", rows: 8, cols: 5, items: 5, background: 0xfafafa, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 0, allowGem: false, gemsStartCount: 0, movesGoal: 20, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: true, roverStartCount: 4, win: { orange: 4, rover: 3, }, blocks: [{ "row": 1, "col": 1 }, { "row": 1, "col": 2 }, { "row": 2, "col": 1 }, { "row": 2, "col": 2 }] },
  { tittle: "Wild", rows: 8, cols: 7, items: 5, background: 0xfafafa, allowWild: true, wildStartCount: 5, allowDrop: false, dropStartCount: 0, allowGem: false, gemsStartCount: 0, movesGoal: 20, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { orange: 5, green: 10, }, blocks: [] },
  { tittle: "Drop", rows: 8, cols: 7, items: 4, background: 0xfafafa, allowWild: false, wildStartCount: 5, allowDrop: true, dropStartCount: 5, allowGem: false, gemsStartCount: 0, movesGoal: 20, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { orange: 5, green: 10, drop: 3 }, blocks: [] },
  { tittle: "Gem", rows: 8, cols: 7, items: 5, background: 0xfafafa, allowWild: false, wildStartCount: 5, allowDrop: false, dropStartCount: 5, allowGem: true, gemsStartCount: 4, movesGoal: 20, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { orange: 5, green: 10, gem: 3 }, blocks: [] },
  { tittle: "Rover", rows: 8, cols: 7, items: 5, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 0, allowGem: false, gemsStartCount: 0, movesGoal: 20, allowIce: false, iceStartCount: 15, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: true, roverStartCount: 4, win: { blue: 15, orange: 15, rover: 4, }, blocks: [] },
  { tittle: "Ice", rows: 8, cols: 7, items: 5, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 0, allowGem: false, gemsStartCount: 0, movesGoal: 20, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: true, roverStartCount: 4, win: { blue: 15, orange: 15, }, blocks: [] },
  { tittle: "Fire", rows: 8, cols: 7, items: 5, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 0, allowGem: false, gemsStartCount: 0, movesGoal: 20, allowIce: false, iceStartCount: 15, allowFire: true, fireStartCount: 7, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 4, win: { blue: 15, orange: 15, }, blocks: [] },
  { tittle: "Bomb", rows: 8, cols: 7, items: 5, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 0, allowGem: false, gemsStartCount: 0, movesGoal: 20, allowIce: false, iceStartCount: 15, allowFire: false, fireStartCount: 7, allowBomb: true, bombStartCount: 5, allowRover: false, roverStartCount: 4, win: { blue: 15, orange: 15, bomb: 5, }, blocks: [] },
  { tittle: "Square", rows: 8, cols: 7, items: 5, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 0, allowGem: false, gemsStartCount: 0, movesGoal: 20, allowIce: false, iceStartCount: 15, allowFire: false, fireStartCount: 7, allowBomb: false, bombStartCount: 5, allowRover: false, roverStartCount: 4, win: { blue: 15, orange: 15, square: 4, }, blocks: [] },
  { tittle: "Blocks", rows: 8, cols: 7, items: 5, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 0, allowGem: false, gemsStartCount: 0, movesGoal: 20, allowIce: false, iceStartCount: 15, allowFire: false, fireStartCount: 7, allowBomb: false, bombStartCount: 5, allowRover: false, roverStartCount: 4, win: { blue: 15, orange: 15, }, blocks: [{ "row": 3, "col": 2 }, { "row": 3, "col": 3 }, { "row": 3, "col": 4 }, { "row": 4, "col": 2 }, { "row": 4, "col": 3 }, { "row": 4, "col": 4 }] },
  { tittle: "Drop Gem", rows: 8, cols: 7, items: 5, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: true, dropStartCount: 3, allowGem: true, gemsStartCount: 3, movesGoal: 20, allowIce: false, iceStartCount: 15, allowFire: false, fireStartCount: 7, allowBomb: false, bombStartCount: 5, allowRover: false, roverStartCount: 4, win: { blue: 15, orange: 15, drop: 3, gem: 3, }, blocks: [] },
  { tittle: "rover ice", rows: 8, cols: 7, items: 5, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 3, allowGem: false, gemsStartCount: 3, movesGoal: 30, allowIce: true, iceStartCount: 15, allowFire: false, fireStartCount: 7, allowBomb: false, bombStartCount: 5, allowRover: true, roverStartCount: 4, win: { blue: 15, orange: 15, ice: 10, rover: 4 }, blocks: [] },

  { tittle: "1", rows: 6, cols: 4, items: 4, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 3, allowGem: false, gemsStartCount: 0, movesGoal: 10, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 5, orange: 5, purple: 5, }, blocks: [] },
  { tittle: "2", rows: 6, cols: 4, items: 4, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 3, allowGem: false, gemsStartCount: 0, movesGoal: 15, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 10, orange: 10, green: 10, purple: 10, square: 5, }, blocks: [] },
  { tittle: "3", rows: 6, cols: 5, items: 4, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 3, allowGem: false, gemsStartCount: 0, movesGoal: 20, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 10, orange: 20, green: 10, purple: 20, square: 7, }, blocks: [] },
  { tittle: "4", rows: 6, cols: 5, items: 5, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 3, allowGem: false, gemsStartCount: 0, movesGoal: 20, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 15, orange: 15, green: 15, purple: 15, brown: 15, square: 5, }, blocks: [] },
  { tittle: "5", rows: 6, cols: 5, items: 6, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 3, allowGem: false, gemsStartCount: 0, movesGoal: 30, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { red: 15, blue: 15, orange: 15, green: 15, purple: 15, brown: 15, }, blocks: [] },
  { tittle: "6", rows: 6, cols: 6, items: 5, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 3, allowGem: false, gemsStartCount: 0, movesGoal: 25, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 30, orange: 30, green: 30, purple: 30, brown: 30, square: 5, }, blocks: [] },
  { tittle: "7", rows: 6, cols: 6, items: 4, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 3, allowGem: false, gemsStartCount: 0, movesGoal: 25, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 30, orange: 30, green: 30, purple: 30, square: 5, }, blocks: [{ "row": 0, "col": 0 }, { "row": 0, "col": 1 }, { "row": 1, "col": 0 }, { "row": 1, "col": 1 }, { "row": 4, "col": 4 }, { "row": 4, "col": 5 }, { "row": 5, "col": 4 }, { "row": 5, "col": 5 }] },
  { tittle: "8", rows: 6, cols: 4, items: 4, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 3, allowGem: false, gemsStartCount: 0, movesGoal: 25, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { square: 10, }, blocks: [] },
  { tittle: "9", rows: 6, cols: 4, items: 4, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 3, allowGem: false, gemsStartCount: 0, movesGoal: 10, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { square: 5, }, blocks: [] },
  { tittle: "10", rows: 6, cols: 4, items: 5, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 3, allowGem: false, gemsStartCount: 0, movesGoal: 20, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { square: 5, }, blocks: [] },
  { tittle: "11", rows: 6, cols: 4, items: 5, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 3, allowGem: false, gemsStartCount: 0, movesGoal: 20, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 15, purple: 15, square: 5, }, blocks: [] },
  { tittle: "12", rows: 8, cols: 6, items: 5, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: true, dropStartCount: 3, allowGem: false, gemsStartCount: 0, movesGoal: 20, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { orange: 10, drop: 4, }, blocks: [] },

  { tittle: "Drop 1", rows: 8, cols: 7, items: 4, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: true, dropStartCount: 3, allowGem: false, gemsStartCount: 0, movesGoal: 20, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { orange: 20, purple: 20, drop: 3, }, blocks: [] },
  { tittle: "Drop 2", rows: 8, cols: 5, items: 4, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: true, dropStartCount: 3, allowGem: false, gemsStartCount: 0, movesGoal: 20, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { orange: 20, purple: 20, drop: 6, }, blocks: [] },
  { tittle: "Drop 3", rows: 8, cols: 5, items: 5, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: true, dropStartCount: 1, allowGem: false, gemsStartCount: 0, movesGoal: 25, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { orange: 15, purple: 15, drop: 3, }, blocks: [] },
  { tittle: "Drop 4", rows: 8, cols: 4, items: 4, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: true, dropStartCount: 3, allowGem: false, gemsStartCount: 0, movesGoal: 25, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { purple: 15, drop: 8, }, blocks: [] },
  { tittle: "Drop 5", rows: 8, cols: 7, items: 5, background: 0x000000, allowWild: true, wildStartCount: 2, allowDrop: true, dropStartCount: 5, allowGem: false, gemsStartCount: 0, movesGoal: 25, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 20, purple: 20, square: 5, drop: 10, }, blocks: [] },
  { tittle: "Drop 6", rows: 9, cols: 7, items: 5, background: 0x000000, allowWild: true, wildStartCount: 2, allowDrop: true, dropStartCount: 3, allowGem: false, gemsStartCount: 0, movesGoal: 25, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 20, green: 20, purple: 20, drop: 10, }, blocks: [] },
  { tittle: "Drop 7", rows: 9, cols: 7, items: 4, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: true, dropStartCount: 4, allowGem: false, gemsStartCount: 0, movesGoal: 30, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 20, green: 20, purple: 20, drop: 15, }, blocks: [{ "row": 2, "col": 2 }, { "row": 2, "col": 3 }, { "row": 2, "col": 4 }, { "row": 3, "col": 1 }, { "row": 3, "col": 2 }, { "row": 3, "col": 3 }, { "row": 3, "col": 4 }, { "row": 3, "col": 5 }, { "row": 4, "col": 1 }, { "row": 4, "col": 2 }, { "row": 4, "col": 3 }, { "row": 4, "col": 4 }, { "row": 4, "col": 5 }, { "row": 5, "col": 2 }, { "row": 5, "col": 3 }, { "row": 5, "col": 4 }] },
  { tittle: "Drop 8", rows: 8, cols: 7, items: 6, background: 0x000000, allowWild: true, wildStartCount: 2, allowDrop: true, dropStartCount: 3, allowGem: false, gemsStartCount: 0, movesGoal: 20, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 20, green: 20, purple: 20, square: 3, drop: 8, }, blocks: [] },
  { tittle: "Drop 9", rows: 9, cols: 4, items: 3, background: 0x000000, allowWild: true, wildStartCount: 2, allowDrop: true, dropStartCount: 1, allowGem: false, gemsStartCount: 0, movesGoal: 20, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 20, purple: 20, square: 3, drop: 15, }, blocks: [] },
  { tittle: "Drop 10", rows: 9, cols: 4, items: 6, background: 0x000000, allowWild: true, wildStartCount: 2, allowDrop: true, dropStartCount: 1, allowGem: false, gemsStartCount: 0, movesGoal: 15, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 7, orange: 7, purple: 7, square: 3, drop: 3, }, blocks: [] },
  { tittle: "Drop 11", rows: 10, cols: 4, items: 5, background: 0x000000, allowWild: false, wildStartCount: 2, allowDrop: true, dropStartCount: 1, allowGem: false, gemsStartCount: 0, movesGoal: 25, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 7, orange: 7, purple: 7, drop: 7, ice: 1, }, blocks: [{ "row": 3, "col": 0 }, { "row": 3, "col": 3 }, { "row": 4, "col": 0 }, { "row": 4, "col": 3 }, { "row": 5, "col": 0 }, { "row": 5, "col": 3 }, { "row": 6, "col": 0 }, { "row": 6, "col": 3 }] },
  { tittle: "Drop 12", rows: 10, cols: 4, items: 4, background: 0x000000, allowWild: false, wildStartCount: 2, allowDrop: true, dropStartCount: 2, allowGem: false, gemsStartCount: 0, movesGoal: 25, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 13, orange: 7, purple: 10, drop: 10, ice: 1, }, blocks: [{ "row": 8, "col": 0 }, { "row": 8, "col": 1 }, { "row": 8, "col": 2 }, { "row": 8, "col": 3 }, { "row": 9, "col": 0 }, { "row": 9, "col": 1 }, { "row": 9, "col": 2 }, { "row": 9, "col": 3 }] },

  { tittle: "Gem 1", rows: 8, cols: 7, items: 4, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 0, allowGem: true, gemsStartCount: 4, movesGoal: 20, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 11, green: 11, purple: 11, gem: 6, }, blocks: [] },
  { tittle: "Gem 2", rows: 8, cols: 7, items: 4, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: false, dropStartCount: 0, allowGem: true, gemsStartCount: 4, movesGoal: 10, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 11, green: 11, purple: 11, gem: 4, }, blocks: [] },
  { tittle: "Gem 3", rows: 8, cols: 7, items: 5, background: 0x000000, allowWild: false, wildStartCount: 1, allowDrop: false, dropStartCount: 0, allowGem: true, gemsStartCount: 4, movesGoal: 17, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 11, green: 11, purple: 11, gem: 8, }, blocks: [] },
  { tittle: "Gem 4", rows: 8, cols: 8, items: 6, background: 0x000000, allowWild: false, wildStartCount: 3, allowDrop: false, dropStartCount: 0, allowGem: true, gemsStartCount: 2, movesGoal: 25, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 11, orange: 11, green: 11, purple: 11, gem: 9, }, blocks: [] },
  { tittle: "Gem 5", rows: 9, cols: 5, items: 5, background: 0x000000, allowWild: false, wildStartCount: 1, allowDrop: false, dropStartCount: 0, allowGem: true, gemsStartCount: 4, movesGoal: 25, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 11, orange: 11, green: 11, purple: 11, gem: 5, }, blocks: [] },
  { tittle: "Gem 6", rows: 9, cols: 6, items: 5, background: 0x000000, allowWild: true, wildStartCount: 3, allowDrop: false, dropStartCount: 0, allowGem: true, gemsStartCount: 5, movesGoal: 25, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 15, orange: 15, green: 15, purple: 15, gem: 5, }, blocks: [] },
  { tittle: "Gem 7", rows: 9, cols: 6, items: 4, background: 0x000000, allowWild: false, wildStartCount: 3, allowDrop: true, dropStartCount: 3, allowGem: true, gemsStartCount: 3, movesGoal: 25, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 15, orange: 15, green: 15, purple: 15, drop: 5, gem: 5, }, blocks: [] },
  { tittle: "Gem 8", rows: 9, cols: 6, items: 4, background: 0x000000, allowWild: false, wildStartCount: 3, allowDrop: true, dropStartCount: 1, allowGem: true, gemsStartCount: 1, movesGoal: 30, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 20, orange: 20, purple: 20, square: 5, drop: 5, gem: 5, }, blocks: [] },
  { tittle: "Gem 9", rows: 9, cols: 7, items: 5, background: 0x000000, allowWild: true, wildStartCount: 1, allowDrop: true, dropStartCount: 2, allowGem: true, gemsStartCount: 2, movesGoal: 30, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 20, orange: 20, green: 20, purple: 20, drop: 5, gem: 5, }, blocks: [] },
  { tittle: "Gem 10", rows: 5, cols: 7, items: 4, background: 0x000000, allowWild: true, wildStartCount: 1, allowDrop: true, dropStartCount: 3, allowGem: true, gemsStartCount: 3, movesGoal: 30, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 20, orange: 20, green: 20, purple: 20, drop: 5, gem: 5, }, blocks: [] },
  { tittle: "Gem 11", rows: 9, cols: 7, items: 5, background: 0x000000, allowWild: true, wildStartCount: 2, allowDrop: true, dropStartCount: 2, allowGem: true, gemsStartCount: 2, movesGoal: 30, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 20, green: 20, purple: 20, drop: 8, }, blocks: [{ "row": 6, "col": 0 }, { "row": 6, "col": 6 }, { "row": 7, "col": 0 }, { "row": 7, "col": 1 }, { "row": 7, "col": 5 }, { "row": 7, "col": 6 }, { "row": 8, "col": 0 }, { "row": 8, "col": 1 }, { "row": 8, "col": 2 }, { "row": 8, "col": 4 }, { "row": 8, "col": 5 }, { "row": 8, "col": 6 }] },
  { tittle: "Gem 12", rows: 9, cols: 7, items: 4, background: 0x000000, allowWild: false, wildStartCount: 0, allowDrop: true, dropStartCount: 3, allowGem: true, gemsStartCount: 3, movesGoal: 23, allowIce: false, iceStartCount: 0, allowFire: false, fireStartCount: 0, allowBomb: false, bombStartCount: 0, allowRover: false, roverStartCount: 0, win: { blue: 20, green: 20, purple: 20, drop: 15, }, blocks: [{ "row": 3, "col": 0 }, { "row": 3, "col": 6 }, { "row": 4, "col": 0 }, { "row": 4, "col": 1 }, { "row": 4, "col": 5 }, { "row": 4, "col": 6 }, { "row": 5, "col": 0 }, { "row": 5, "col": 6 }, { "row": 7, "col": 3 }, { "row": 8, "col": 2 }, { "row": 8, "col": 3 }, { "row": 8, "col": 4 }] },
]






